spring:
  datasource:
    url: jdbc:mysql://localhost:3306/group1_user?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: localhost
server:
  port: 8080
  servlet:
    context-path: /api